### ISSUE TITLE
Create escrow release

### ISSUE THREAD

**Issue by ruanltbg** [wirecardBrasil/moip-sdk-ruby#76]
There is no way to release an escrow by the SDK. I had to do it manually as:
```ruby
moip_api.client.post('/v2/escrows/ECW-ID/release', '')
```
It would be great to have this inside the SDK, something like:
```
moip_api.escrow.release('ECW-ID')
```

Doc:
https://dev.moip.com.br/v2/reference#libera%C3%A7%C3%A3o-de-cust%C3%B3dia

**Comment by bressani** [comment]
Hello!

It's on our backlog, but probably it's not going to be developed in the next few weeks, due to the very small team that takes care of the Moip's SDKs.

But feel free to send us a PR with this feature. 😄 

Thank you very much!

**Comment by mateusluizfb** [comment]
Any news? Can I do the changes and make the PR?

**Comment by ruanltbg** [comment]
@mateusluizfb Yes, for me.

**Comment by bressani** [comment]
Hello @mateusluizfb and @ruanltbg , it's about to be released:

https://github.com/moip/moip-sdk-ruby/pull/80/commits/ef61c2d0ad903a0944f2b69348421f697ae04914

@MbNakaya can you help them with this, please?

**Comment by mateusluizfb** [comment]
@bressani nice! Thanks for the update!

**Comment by mateusluizfb** [comment]
Any news?

**Comment by ruanltbg** [comment]
The code is merged into master, I will close this.
